import {
  Calculator,
  Beef,
  Scale,
  Activity,
  Target,
  Dumbbell,
  Droplets,
  ArrowLeftRight,
  Camera,
  TrendingUp,
  Coffee,
  Clock,
  BarChart2,
} from "lucide-react";

export const CALCULATORS = [
  {
    href: "/tools/calorie-calculator",
    icon: Calculator,
    title: "Calorie Calculator",
    description: "Estimate daily calories to maintain your current weight across all activity levels.",
    iconBg: "bg-orange-50 border-orange-100 text-orange-500",
  },
  {
    href: "/tools/macro-calculator",
    icon: Beef,
    title: "Macro Calculator",
    description: "Find your ideal daily protein, carb, and fat targets tailored to your goal.",
    iconBg: "bg-red-50 border-red-100 text-red-500",
  },
  {
    href: "/tools/bmi",
    icon: Scale,
    title: "BMI Calculator",
    description: "Body Mass Index — a quick height-and-weight screening with a visual gauge.",
    iconBg: "bg-purple-50 border-purple-100 text-purple-500",
  },
  {
    href: "/tools/body-fat",
    icon: Activity,
    title: "Body Fat % Estimator",
    description: "U.S. Navy tape-measure method — no calipers needed. Get your estimated BF% category.",
    iconBg: "bg-blue-50 border-blue-100 text-blue-500",
  },
  {
    href: "/tools/ideal-weight",
    icon: Target,
    title: "Ideal Weight Calculator",
    description: "Four clinical formulas (Devine, Robinson, Miller, Hamwi) with a recommended range.",
    iconBg: "bg-green-50 border-green-100 text-green-500",
  },
  {
    href: "/tools/protein",
    icon: Beef,
    title: "Protein Calculator",
    description: "Daily protein targets by goal and activity level, with a meal-by-meal breakdown.",
    iconBg: "bg-rose-50 border-rose-100 text-rose-500",
  },
  {
    href: "/tools/one-rep-max",
    icon: Dumbbell,
    title: "One-Rep Max (1RM)",
    description: "Estimate your max lift and get a full training-zone weight chart.",
    iconBg: "bg-amber-50 border-amber-100 text-amber-500",
  },
  {
    href: "/tools/water",
    icon: Droplets,
    title: "Water Intake Calculator",
    description: "Daily hydration target in oz, mL, and cups — plus an hourly sip schedule.",
    iconBg: "bg-sky-50 border-sky-100 text-sky-500",
  },
  {
    href: "/tools/plate-converter",
    icon: ArrowLeftRight,
    title: "Plate Converter",
    description: "Convert kg ↔ lbs for plates and bars. Includes a barbell load calculator with a visual plate diagram.",
    iconBg: "bg-slate-50 border-slate-200 text-slate-500",
  },
  {
    href: "/tools/meal-photo",
    icon: Camera,
    title: "Meal Photo Analyzer",
    description: "Snap or upload a photo of any meal — AI estimates calories, protein, carbs, and fat instantly.",
    iconBg: "bg-violet-50 border-violet-100 text-violet-500",
  },
  {
    href: "/tools/adaptive-tdee",
    icon: TrendingUp,
    title: "Adaptive TDEE Calculator",
    description: "Uses your actual weight trend to back-calculate your true maintenance calories — beats any formula.",
    iconBg: "bg-emerald-50 border-emerald-100 text-emerald-500",
  },
  {
    href: "/tools/reverse-diet",
    icon: TrendingUp,
    title: "Reverse Dieting Planner",
    description: "Week-by-week calorie ramp-up schedule after a cut — add food back without gaining fat.",
    iconBg: "bg-teal-50 border-teal-100 text-teal-500",
  },
  {
    href: "/tools/diet-break",
    icon: Coffee,
    title: "Diet Break Planner",
    description: "Know when to take a strategic maintenance break to restore hormones and keep fat loss moving.",
    iconBg: "bg-amber-50 border-amber-100 text-amber-500",
  },
  {
    href: "/tools/fasting",
    icon: Clock,
    title: "Intermittent Fasting Planner",
    description: "Pick a protocol (16:8, 18:6, OMAD, 5:2) and get your daily eating window with macro tips.",
    iconBg: "bg-indigo-50 border-indigo-100 text-indigo-500",
  },
  {
    href: "/tools/visceral-fat",
    icon: Activity,
    title: "Visceral Fat Risk Estimator",
    description: "Waist-to-height ratio — a stronger predictor of metabolic disease risk than BMI.",
    iconBg: "bg-pink-50 border-pink-100 text-pink-500",
  },
  {
    href: "/tools/periodization",
    icon: BarChart2,
    title: "Cut / Bulk / Maintain Planner",
    description: "Get a phased plan: when to cut, when to bulk, and what to eat in each phase based on your body fat.",
    iconBg: "bg-cyan-50 border-cyan-100 text-cyan-500",
  },
];

export const STATIC_GUIDES = [
  {
    href: "/tools/guides/reading-labels",
    title: "How to Read a Nutrition Label",
    description: "Decode serving sizes, % DV, and hidden sugars in under 2 minutes.",
    emoji: "🏷️",
  },
  {
    href: "/tools/guides/high-protein-swaps",
    title: "High-Protein Food Swaps",
    description: "Simple substitutions to hit your protein goal without overhauling your diet.",
    emoji: "💪",
  },
  {
    href: "/tools/guides/understanding-macros",
    title: "Understanding Macros",
    description: "What protein, carbs, and fat actually do — and how much you need of each.",
    emoji: "📊",
  },
  {
    href: "/tools/guides/keto-101",
    title: "Keto 101",
    description: "How ketosis works, what to expect week by week, electrolytes, and the most common mistakes.",
    emoji: "🥑",
  },
  {
    href: "/tools/guides/keto-food-list",
    title: "Keto Food List",
    description: "Complete eat / avoid / moderation lists with net carb counts for every category.",
    emoji: "🥩",
  },
  {
    href: "/tools/guides/keto-macros",
    title: "Keto Macros Guide",
    description: "Step-by-step: calculate your personal fat, protein, and carb targets for keto.",
    emoji: "📊",
  },
  {
    href: "/tools/guides/supplements",
    title: "Supplement Evidence Guide",
    description: "Evidence ratings (A–D) for 15 popular supplements — dose, timing, side effects, and who it's for.",
    emoji: "💊",
  },
  {
    href: "/tools/guides/cycle-nutrition",
    title: "Menstrual Cycle Nutrition Guide",
    description: "How to adjust macros, calories, and training across all 4 cycle phases for better results.",
    emoji: "🌸",
  },
];
