import type { Metadata } from "next";
import { LegalPageShell } from "@/components/legal/LegalPageShell";

export const metadata: Metadata = {
  title: "Terms & License — LeanOut AI",
  description: "Terms of Service and software license for LeanOut AI.",
};

export default function LicensePage() {
  return (
    <LegalPageShell
      title="Terms & License"
      subtitle="The agreement between you and LeanOut AI for using our software and services."
      lastUpdated="June 12, 2026"
    >
      <p>
        These Terms of Service (&quot;Terms&quot;) govern your access to and use of LeanOut AI at
        leanout.app and related mobile applications (the &quot;Service&quot;), operated by Michael Lynn
        (&quot;we,&quot; &quot;us&quot;). By creating an account or using the Service, you agree to
        these Terms and our <a href="/privacy">Privacy Policy</a>.
      </p>

      <h2>Software license</h2>
      <p>
        Subject to these Terms, we grant you a personal, non-exclusive, non-transferable, revocable
        license to access and use the LeanOut software for your own fitness and nutrition tracking. You
        may not copy, modify, distribute, sell, lease, reverse engineer, or create derivative works
        from the Service or its underlying code, except as permitted by applicable law.
      </p>

      <h2>Eligibility</h2>
      <p>
        You must be at least 18 years old (or the age of majority in your jurisdiction) to use LeanOut.
        If you are using the Service on behalf of an organization, you represent that you have authority
        to bind that organization to these Terms.
      </p>

      <h2>Your account</h2>
      <p>
        You are responsible for maintaining the confidentiality of your login credentials and for all
        activity under your account. Notify us promptly at{" "}
        <a href="mailto:contact@leanout.ai">contact@leanout.ai</a> if you suspect unauthorized access.
      </p>

      <h2>Acceptable use</h2>
      <p>You agree not to:</p>
      <ul>
        <li>Use the Service for any unlawful purpose or to harm others</li>
        <li>Attempt to gain unauthorized access to accounts, systems, or data</li>
        <li>Scrape, crawl, or automate access beyond normal app use without permission</li>
        <li>Upload malware, spam, or content that infringes third-party rights</li>
        <li>Circumvent usage limits, billing controls, or security measures</li>
        <li>Misrepresent AI-generated coaching as professional medical or dietetic advice</li>
      </ul>

      <h2>Health and fitness disclaimer</h2>
      <p>
        LeanOut provides general fitness and nutrition information and AI-generated suggestions. It is{" "}
        <strong>not</strong> medical advice, diagnosis, or treatment. Consult a qualified healthcare
        provider before starting any diet, exercise program, or if you have a medical condition,
        pregnancy, eating disorder history, or take medications affected by diet or activity changes.
        You use the Service at your own risk.
      </p>

      <h2>AI-generated content</h2>
      <p>
        Meal plans, coach messages, food estimates, and workout suggestions are generated by artificial
        intelligence and may be inaccurate or incomplete. You are responsible for verifying nutritional
        information, portion sizes, and exercise suitability before acting on AI output.
      </p>

      <h2>Free and Pro plans</h2>
      <p>
        Core features are available on the free tier subject to usage limits described in the app. LeanOut
        Pro is a paid subscription with additional AI and automation features when billing is enabled.
        Prices, limits, and features may change with notice in the app. Subscriptions renew automatically
        until canceled through Stripe or your app store, where applicable. Refunds are handled per
        Stripe&apos;s and applicable store policies unless we state otherwise.
      </p>

      <h2>Your content</h2>
      <p>
        You retain ownership of data you submit (logs, photos, messages). You grant us a limited license
        to host, process, and display that content solely to operate and improve the Service, including
        sending relevant portions to AI providers as described in our Privacy Policy.
      </p>

      <h2>Intellectual property</h2>
      <p>
        LeanOut AI, its branding, design, and software are owned by us or our licensors. These Terms do
        not grant you any rights to our trademarks or logos except as needed to use the Service as
        intended.
      </p>

      <h2>Third-party services</h2>
      <p>
        The Service integrates with third parties (payment, AI, health platforms, food databases). Your
        use of those features may be subject to additional third-party terms. We are not responsible for
        third-party services outside our reasonable control.
      </p>

      <h2>Termination</h2>
      <p>
        You may stop using LeanOut at any time. We may suspend or terminate access if you violate these
        Terms, create security risk, or if we discontinue the Service. Upon termination, your license
        ends and we may delete your account data per our Privacy Policy.
      </p>

      <h2>Disclaimers</h2>
      <p>
        THE SERVICE IS PROVIDED &quot;AS IS&quot; AND &quot;AS AVAILABLE&quot; WITHOUT WARRANTIES OF ANY
        KIND, EXPRESS OR IMPLIED, INCLUDING MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND
        NON-INFRINGEMENT. WE DO NOT WARRANT UNINTERRUPTED OR ERROR-FREE OPERATION.
      </p>

      <h2>Limitation of liability</h2>
      <p>
        TO THE MAXIMUM EXTENT PERMITTED BY LAW, WE AND OUR SUPPLIERS WILL NOT BE LIABLE FOR INDIRECT,
        INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR ANY LOSS OF PROFITS, DATA, OR GOODWILL,
        ARISING FROM YOUR USE OF THE SERVICE. OUR TOTAL LIABILITY FOR ANY CLAIM RELATING TO THE SERVICE
        IS LIMITED TO THE GREATER OF (A) AMOUNTS YOU PAID US IN THE TWELVE MONTHS BEFORE THE CLAIM OR
        (B) USD $100.
      </p>

      <h2>Indemnification</h2>
      <p>
        You agree to indemnify and hold us harmless from claims arising out of your misuse of the
        Service, violation of these Terms, or infringement of third-party rights.
      </p>

      <h2>Governing law</h2>
      <p>
        These Terms are governed by the laws of the State of California, USA, without regard to conflict
        of law principles, except where mandatory consumer protections in your country apply. Disputes
        will be resolved in the courts of California unless otherwise required by law.
      </p>

      <h2>Changes</h2>
      <p>
        We may update these Terms. We will post the revised version with an updated date. Material
        changes may also be communicated in-app or by email. Continued use after changes constitutes
        acceptance.
      </p>

      <h2>Contact</h2>
      <p>
        Questions about these Terms:{" "}
        <a href="mailto:contact@leanout.ai">contact@leanout.ai</a>
      </p>
    </LegalPageShell>
  );
}
